### ISSUE TITLE
Twitter alternative

### ISSUE THREAD

**Issue by Snarkly** [brandonhimpfen/twitter#1]
You need to make a Twitter alternative like the old Twitter in this picture and get it up and running for people to use. People are looking for a good Twitter alternative because Twitter has gone down hill. They censor everything now and shadowban people. I've done a little research and people seem to want features like Twitter removed. People want to use gifs for avatars and they want to be able to upload an image to use as their background just like in this example picture. I would even give it a name like Tweetter, it's close to Twitter and it would attract a lot of people to it. If you can create a good Twitter replace I will promote it. ![twitterclone](https://cloud.githubusercontent.com/assets/8492776/24215469/3a098b70-0f0f-11e7-92c6-482152bb7e52.png)

**Comment by brandonhimpfen** [comment]
This repo has nothing to do with creating a Twitter alternative.
